import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header/Header";
import logo from "../assets/svg/Logo.svg";
import { menu } from "@/data/menu";
import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
  Skeleton,
  Text,
} from "@chakra-ui/react";
import dynamic from "next/dynamic";
import Testimonials from "@/components/testimonial/Testimonials";
import Faq from "@/components/faq/Faq";
import SeoTable from "@/components/seo/SeoTable";
import ContentBlock from "@/components/content-block/ContentBlock";
const Playground = dynamic(
  () => import("@/components/paraphraser/playground/Playground"),
  {
    ssr: false,
    loading: () => <Skeleton></Skeleton>,
  }
);
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header logo={logo} menu={menu} />
        <Box
          mt={["15px", "25px"]}
          display={"flex"}
          alignItems={"center"}
          flexDirection={"column"}
        >
          <Box w={["90%", "90%", "85%"]}>
            <Text fontSize={["25px", "30px"]} fontWeight="700">
              Paraphraser
            </Text>
            <Playground />
          </Box>
          <ContentBlock
            theme="secondary"
            title={"How AI Content Detection Works?"}
            content={
              "It is difficult to detect any kind of content, but it is almost impossible to get an accuracy rate close to 100% when detecting AI content. This detection model was developed by combining and fine-tuning the results of Open AI's GPT 2 model with the outputs of a robustly optimized BERT pretraining approach (Roberta) model. To determine whether the content was created by AI, users need to utilize this tool along with their judgment."
            }
          />
          <SeoTable />
          <Testimonials />
          <Faq />
        </Box>
      </main>
    </>
  );
}
